server:
  port: 8081
  servlet:
    context-path: /sts
    encoding:
      charset: UTF-8
      
spring:
  messages:
    basename: base,errors
    encoding: UTF-8
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
